"""Generate golden reference trajectories from the Python physics core.

This is the mechanism that makes Python the *source of truth*: it runs a set of
representative scenarios through the authoritative ``double_pendulum`` package
and writes the resulting trajectories to ``golden/golden.json``.  The TypeScript
suite (``src/__tests__/parity.test.ts``) then re-runs the identical scenarios
through the code that ships to the browser and asserts a match to within a tight
tolerance.  Regenerating and diffing this file in CI guarantees the committed
golden always reflects the current Python source.

Run with::

    python -m parity.generate          # from the python/ directory

Params are serialised using the JavaScript field names (camelCase where the TS
type uses it) so the JS test can feed them straight into its ``Params`` object.
"""

from __future__ import annotations

import json
import math
import os
from typing import Any, Dict, List

from double_pendulum import Params, Simulation
from double_pendulum.presets import default_params, presets

# Number of physics steps to record per scenario. Short enough that chaotic
# scenarios stay well within the parity tolerance (trajectories only diverge
# from last-ULP trig differences, which grow slowly over this horizon), long
# enough to exercise many integration steps.
STEPS = 200

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN_PATH = os.path.join(os.path.dirname(HERE), "golden", "golden.json")


def _forcing_to_js(f) -> Dict[str, Any]:
    return {
        "type": f.type,
        "amplitude": f.amplitude,
        "frequency": f.frequency,
        "phase": f.phase,
        "noiseIntensity": f.noise_intensity,
    }


def params_to_js(p: Params) -> Dict[str, Any]:
    """Serialise Params with the JavaScript/TypeScript field names."""

    return {
        "m1": p.m1, "m2": p.m2, "l1": p.l1, "l2": p.l2, "g": p.g,
        "b1": p.b1, "b2": p.b2,
        "theta1_0": p.theta1_0, "theta2_0": p.theta2_0,
        "omega1_0": p.omega1_0, "omega2_0": p.omega2_0,
        "forcing1": _forcing_to_js(p.forcing1),
        "forcing2": _forcing_to_js(p.forcing2),
        "pivot": {"mode": p.pivot.mode, "amplitude": p.pivot.amplitude,
                  "frequency": p.pivot.frequency},
        "dt": p.dt, "speed": p.speed, "trailLength": p.trail_length,
        "seed": p.seed, "impulseMagnitude": p.impulse_magnitude,
        "comparison": p.comparison, "epsilon": p.epsilon,
    }


def _record_to_js(r) -> Dict[str, Any]:
    return {
        "t": r.t, "th1": r.th1, "th2": r.th2, "w1": r.w1, "w2": r.w2,
        "ke": r.ke, "pe": r.pe, "e": r.e,
        "tau1": r.tau1, "tau2": r.tau2, "pext": r.pext, "pdamp": r.pdamp,
        "d": r.d, "lyap": r.lyap,
    }


def run_scenario(name: str, params: Params) -> Dict[str, Any]:
    sim = Simulation(params)
    for _ in range(STEPS):
        sim.step()
    return {
        "name": name,
        "params": params_to_js(params),
        "steps": STEPS,
        "history": [_record_to_js(r) for r in sim.history],
    }


def build_scenarios() -> List[Dict[str, Any]]:
    scenarios: List[Dict[str, Any]] = []

    # Every named preset — covers none/sine/random forcing, damping, comparison.
    for preset in presets():
        scenarios.append(run_scenario(f"preset: {preset.name}", preset.params))

    # Horizontal moving pivot (exercises pivot_acceleration, horizontal branch).
    hpivot = default_params()
    hpivot.theta1_0, hpivot.theta2_0 = 30 * math.pi / 180, 10 * math.pi / 180
    hpivot.pivot.mode = "horizontal"
    hpivot.pivot.amplitude = 0.2
    hpivot.pivot.frequency = 1.5
    scenarios.append(run_scenario("horizontal moving pivot", hpivot))

    # Vertical pivot + constant torque on joint 1 + square wave on joint 2.
    vpivot = default_params()
    vpivot.theta1_0, vpivot.theta2_0 = 45 * math.pi / 180, 20 * math.pi / 180
    vpivot.b1, vpivot.b2 = 0.05, 0.05
    vpivot.pivot.mode = "vertical"
    vpivot.pivot.amplitude = 0.15
    vpivot.pivot.frequency = 2.0
    vpivot.forcing1.type = "constant"
    vpivot.forcing1.amplitude = 1.5
    vpivot.forcing2.type = "square"
    vpivot.forcing2.amplitude = 2.0
    vpivot.forcing2.frequency = 0.8
    scenarios.append(run_scenario("vertical pivot + constant + square forcing", vpivot))

    return scenarios


def main() -> None:
    data = {
        "description": (
            "Golden reference trajectories generated by the authoritative Python "
            "physics core (double_pendulum). The JS parity test must reproduce "
            "these to within tolerance."
        ),
        "steps": STEPS,
        "scenarios": build_scenarios(),
    }
    os.makedirs(os.path.dirname(GOLDEN_PATH), exist_ok=True)
    with open(GOLDEN_PATH, "w") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    print(f"wrote {GOLDEN_PATH}: {len(data['scenarios'])} scenarios x {STEPS} steps")


if __name__ == "__main__":
    main()
